
	import fs from 'fs';
	import path from 'path';

	console.log(atob("DQrilpHilpEgICAgICDilpHilpHilpHilpEgICAgICDilpHilpHilpEgIOKWkeKWkeKWkeKWkSAg4paR4paRICAgICAgIOKWkeKWkeKWkeKWkSAgICAgIOKWkeKWkeKWkSAg4paR4paR4paR4paRICDilpHilpHilpEgICAgICDilpHilpHilpEgICAgICAgIOKWkeKWkSAg4paR4paR4paR4paR4paR4paR4paRDQrilpIgIOKWkuKWkuKWkuKWkiAg4paS4paSICDilpLilpLilpLilpIgIOKWkuKWkiAgIOKWkuKWkiAgIOKWkuKWkiAg4paS4paS4paS4paSICDilpLilpIgIOKWkuKWkuKWkuKWkiAg4paS4paSICAg4paS4paSICAg4paS4paSICDilpLilpLilpLilpIgIOKWkuKWkuKWkuKWkuKWkiAg4paS4paS4paS4paS4paSICDilpLilpLilpLilpLilpLilpLilpINCuKWkyAg4paT4paT4paT4paT4paT4paT4paT4paTICDilpPilpPilpPilpMgIOKWk+KWkyAgICAgICAg4paT4paTICAgICAgIOKWk+KWk+KWkyAg4paT4paT4paT4paTICDilpPilpMgICAgICAgIOKWk+KWkyAg4paT4paT4paT4paTICDilpPilpPilpPilpPilpMgIOKWk+KWk+KWk+KWk+KWkyAg4paT4paT4paT4paT4paT4paT4paTDQriloggIOKWiOKWiOKWiOKWiCAg4paI4paIICDilojilojilojiloggIOKWiOKWiCAg4paIICDiloggIOKWiOKWiCAg4paI4paI4paI4paIICDilojiloggIOKWiOKWiOKWiOKWiCAg4paI4paIICDiloggIOKWiCAg4paI4paIICAgICAgICDilojilojilojilojiloggIOKWiOKWiOKWiOKWiOKWiCAg4paI4paI4paI4paI4paI4paI4paIDQrilojiloggICAgICDilojilojilojiloggICAgICDilojilojiloggIOKWiOKWiOKWiOKWiCAg4paI4paIICAgICAgIOKWiOKWiOKWiOKWiCAgICAgIOKWiOKWiOKWiCAg4paI4paI4paI4paIICDilojiloggIOKWiOKWiOKWiOKWiCAg4paI4paIICAgICAgICDilojiloggICAgICAgIOKWiA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgDQo="))

	if (fs.existsSync(path.resolve("gen"))) fs.rmSync(path.resolve("gen"), { recursive: true });
	if (fs.existsSync(path.resolve("dist"))) fs.rmSync(path.resolve("dist"), { recursive: true });

	fs.mkdirSync(path.resolve("gen/linux"), { recursive: true });
	fs.mkdirSync(path.resolve("gen/win"), { recursive: true });
	fs.mkdirSync(path.resolve("dist"));
